/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssumptionsRouteImport } from './routes/assumptions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as EnvironmentsRouteImport } from './routes/environments'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as ModelPlatformRouteImport } from './routes/model-platform'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as WorkloadRouteImport } from './routes/workload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssumptionsRoute = AssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentsRoute = EnvironmentsRouteImport.update({
  id: '/environments',
  path: '/environments',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPlatformRoute = ModelPlatformRouteImport.update({
  id: '/model-platform',
  path: '/model-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkloadRoute = WorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assumptions': typeof AssumptionsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/environments': typeof EnvironmentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/model-platform': typeof ModelPlatformRoute
  '/results': typeof ResultsRoute
  '/scenarios': typeof ScenariosRoute
  '/workload': typeof WorkloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assumptions': typeof AssumptionsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/environments': typeof EnvironmentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/model-platform': typeof ModelPlatformRoute
  '/results': typeof ResultsRoute
  '/scenarios': typeof ScenariosRoute
  '/workload': typeof WorkloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assumptions': typeof AssumptionsRoute
  '/auth': typeof AuthRoute
  '/compare': typeof CompareRoute
  '/environments': typeof EnvironmentsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/model-platform': typeof ModelPlatformRoute
  '/results': typeof ResultsRoute
  '/scenarios': typeof ScenariosRoute
  '/workload': typeof WorkloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assumptions'
    | '/auth'
    | '/compare'
    | '/environments'
    | '/infrastructure'
    | '/model-platform'
    | '/results'
    | '/scenarios'
    | '/workload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assumptions'
    | '/auth'
    | '/compare'
    | '/environments'
    | '/infrastructure'
    | '/model-platform'
    | '/results'
    | '/scenarios'
    | '/workload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assumptions'
    | '/auth'
    | '/compare'
    | '/environments'
    | '/infrastructure'
    | '/model-platform'
    | '/results'
    | '/scenarios'
    | '/workload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssumptionsRoute: typeof AssumptionsRoute
  AuthRoute: typeof AuthRoute
  CompareRoute: typeof CompareRoute
  EnvironmentsRoute: typeof EnvironmentsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  ModelPlatformRoute: typeof ModelPlatformRoute
  ResultsRoute: typeof ResultsRoute
  ScenariosRoute: typeof ScenariosRoute
  WorkloadRoute: typeof WorkloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assumptions': {
      id: '/assumptions'
      path: '/assumptions'
      fullPath: '/assumptions'
      preLoaderRoute: typeof AssumptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environments': {
      id: '/environments'
      path: '/environments'
      fullPath: '/environments'
      preLoaderRoute: typeof EnvironmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-platform': {
      id: '/model-platform'
      path: '/model-platform'
      fullPath: '/model-platform'
      preLoaderRoute: typeof ModelPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workload': {
      id: '/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof WorkloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssumptionsRoute: AssumptionsRoute,
  AuthRoute: AuthRoute,
  CompareRoute: CompareRoute,
  EnvironmentsRoute: EnvironmentsRoute,
  InfrastructureRoute: InfrastructureRoute,
  ModelPlatformRoute: ModelPlatformRoute,
  ResultsRoute: ResultsRoute,
  ScenariosRoute: ScenariosRoute,
  WorkloadRoute: WorkloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
