// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejrghuhbodveuuuxjbix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcmdodWhib2R2ZXV1dXhqYml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc0NzU4OTYsImV4cCI6MjEwMzA1MTg5Nn0.SJdKXlA-zAuhrXWg-bwzOMBi2l55MdsAtbGl6d0HX84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});